/*
 * Localization system for screen reader strings.
 * All SR announcements use loc(SrStr) to retrieve translated text.
 * Strings are loaded from sr_lang/<language>.txt at startup.
 * Fallback: built-in English defaults (never NULL, never crash).
 */

#pragma once

enum SrStr {
    // General
    SR_MOD_LOADED,
    SR_DEBUG_ON,
    SR_DEBUG_OFF,
    SR_NO_TEXT,

    // World Map
    SR_MAP_EDGE,
    SR_WORLD_MAP,
    SR_DESIGN_WORKSHOP,
    SR_YOUR_TURN,
    SR_UNIT_MOVES_TO,
    SR_TAB_FMT,
    SR_TAB_RESOURCES,
    SR_TAB_CITIZENS,
    SR_TAB_PRODUCTION,
    SR_TERRAIN_OCEAN,
    SR_TERRAIN_SHELF,
    SR_TERRAIN_ROCKY,
    SR_TERRAIN_ROLLING,
    SR_TERRAIN_FLAT,
    SR_FEATURE_FUNGUS,
    SR_FEATURE_FOREST,
    SR_FEATURE_RIVER,
    SR_FEATURE_FARM,
    SR_FEATURE_MINE,
    SR_FEATURE_SOLAR,
    SR_FEATURE_ROAD,
    SR_FEATURE_CONDENSER,
    SR_FEATURE_BOREHOLE,
    SR_FEATURE_BUNKER,
    SR_FEATURE_AIRBASE,
    SR_FEATURE_SENSOR,
    SR_FEATURE_SUPPLY_POD,
    SR_FEATURE_MONOLITH,
    SR_FEATURE_MAGTUBE,
    SR_FEATURE_SOIL_ENRICHER,
    SR_FEATURE_ECH_MIRROR,
    SR_TERRAIN_TRENCH,
    SR_TERRAIN_ARID,
    SR_TERRAIN_MOIST,
    SR_TERRAIN_RAINY,
    SR_TERRAIN_HIGH,
    SR_TILE_YIELDS,
    SR_TILE_OWNER,
    SR_TILE_IN_RADIUS,
    SR_TILE_UNOWNED,
    SR_TILE_UNEXPLORED,

    // Scanner
    SR_SCAN_ALL,
    SR_SCAN_OWN_BASES,
    SR_SCAN_ENEMY_BASES,
    SR_SCAN_ENEMY_UNITS,
    SR_SCAN_OWN_UNITS,
    SR_SCAN_OWN_FORMERS,
    SR_SCAN_FUNGUS,
    SR_SCAN_PODS,
    SR_SCAN_IMPROVEMENTS,
    SR_SCAN_NATURE,
    SR_SCAN_NOT_FOUND,

    SR_BASE_AT,
    SR_UNIT_AT,
    SR_MORE_UNITS,

    // Base Screen
    SR_BASE_SCREEN,
    SR_SEC_OVERVIEW,
    SR_SEC_RESOURCES,
    SR_SEC_PRODUCTION,
    SR_SEC_ECONOMY,
    SR_SEC_FACILITIES,
    SR_SEC_STATUS,
    SR_FMT_OVERVIEW,
    SR_FMT_RESOURCES,
    SR_FMT_PRODUCTION,
    SR_FMT_QUEUE,
    SR_FMT_HURRY_COST,
    SR_FMT_ECONOMY,
    SR_FMT_FACILITIES,
    SR_FMT_FACILITIES_NONE,
    SR_FMT_STATUS,
    SR_FMT_STATUS_NORMAL,
    SR_FMT_DRONE_RIOTS,
    SR_FMT_GOLDEN_AGE,
    SR_FMT_ECO_DAMAGE,
    SR_FMT_GOVERNOR,
    SR_FMT_NERVE_STAPLE,
    SR_FMT_BASE_OPEN,

    // Base Screen (enhanced)
    SR_SEC_UNITS,
    SR_FMT_OVERVIEW_V2,
    SR_FMT_RESOURCES_V2,
    SR_FMT_PRODUCTION_V2,
    SR_FMT_ECONOMY_V2,
    SR_FMT_FACILITIES_V2,
    SR_FMT_UNITS,
    SR_FMT_UNITS_NONE,
    SR_FMT_BASE_OPEN_V2,
    SR_FMT_WORKERS,
    SR_BASE_HELP,
    SR_FMT_TURNS,
    SR_FMT_GROWTH_NEVER,
    SR_FMT_FACTION_CREDITS,
    SR_FMT_FACILITIES_COUNT,

    // Movement & Navigation
    SR_MOVEMENT_POINTS,
    SR_CANNOT_MOVE,

    // Context Help (Ctrl+F1)
    SR_HELP_HEADER,
    SR_HELP_MOVE,
    SR_HELP_EXPLORE,
    SR_HELP_SKIP,
    SR_HELP_HOLD,
    SR_HELP_READ,
    SR_HELP_GOTO,
    SR_HELP_BUILD_BASE,
    SR_HELP_BUILD_ROAD,
    SR_HELP_BUILD_MAGTUBE,
    SR_HELP_BUILD_FARM,
    SR_HELP_BUILD_MINE,
    SR_HELP_BUILD_SOLAR,
    SR_HELP_BUILD_FOREST,
    SR_HELP_BUILD_SENSOR,
    SR_HELP_BUILD_CONDENSER,
    SR_HELP_BUILD_BOREHOLE,
    SR_HELP_BUILD_AIRBASE,
    SR_HELP_BUILD_BUNKER,
    SR_HELP_REMOVE_FUNGUS,
    SR_HELP_AUTOMATE,
    SR_HELP_CONVOY,
    SR_HELP_UNLOAD,
    SR_HELP_OPEN_BASE,
    SR_HELP_MONOLITH,
    SR_HELP_SUPPLY_POD,
    SR_HELP_ATTACK,
    SR_HELP_PROBE,
    SR_HELP_AIRDROP,

    // Hurry feedback
    SR_HURRY_OK,
    SR_HURRY_NO_CREDITS,
    SR_HURRY_CANNOT,

    // Production Picker
    SR_PROD_PICKER_OPEN,
    SR_PROD_PICKER_ITEM,
    SR_PROD_PICKER_SELECT,
    SR_PROD_PICKER_CANCEL,
    SR_PROD_PICKER_EMPTY,
    SR_PROD_PICKER_CURRENT,
    SR_PROD_PICKER_CURRENT_NONE,
    SR_PROD_DETAIL_FAC,
    SR_PROD_DETAIL_PROJECT,
    SR_PROD_DETAIL_UNIT,

    // Menu Bar (world map)
    SR_MENU_GAME,
    SR_MENU_HQ,
    SR_MENU_NETWORK,
    SR_MENU_MAP,
    SR_MENU_ACTION,
    SR_MENU_TERRAFORM,
    SR_MENU_SCENARIO,
    SR_MENU_EDITMAP,
    SR_MENU_HELP,
    SR_MENU_CLOSED,
    SR_MENU_ENTRY_FMT,
    SR_MENU_ITEM_FMT,
    SR_MENU_ITEM_NOHK,
    SR_MENU_NAV_FMT,

    SR_COUNT
};

// Get localized string by ID (never returns NULL)
const char* loc(SrStr id);

// Load language file. Call once at startup after sr_init().
void loc_init();
