/*
 * Localization system for screen reader strings.
 * All SR announcements use loc(SrStr) to retrieve translated text.
 * Strings are loaded from sr_lang/<language>.txt at startup.
 * Fallback: built-in English defaults (never NULL, never crash).
 */

#pragma once

enum SrStr {
    // General
    SR_MOD_LOADED,
    SR_DEBUG_ON,
    SR_DEBUG_OFF,
    SR_NO_TEXT,

    // World Map
    SR_MAP_EDGE,
    SR_WORLD_MAP,
    SR_DESIGN_WORKSHOP,
    SR_YOUR_TURN,
    SR_UNIT_MOVES_TO,
    SR_TAB_FMT,
    SR_TAB_RESOURCES,
    SR_TAB_CITIZENS,
    SR_TAB_PRODUCTION,
    SR_TERRAIN_OCEAN,
    SR_TERRAIN_SHELF,
    SR_TERRAIN_ROCKY,
    SR_TERRAIN_ROLLING,
    SR_TERRAIN_FLAT,
    SR_FEATURE_FUNGUS,
    SR_FEATURE_FOREST,
    SR_FEATURE_RIVER,
    SR_FEATURE_FARM,
    SR_FEATURE_MINE,
    SR_FEATURE_SOLAR,
    SR_FEATURE_ROAD,
    SR_FEATURE_CONDENSER,
    SR_FEATURE_BOREHOLE,
    SR_FEATURE_BUNKER,
    SR_FEATURE_AIRBASE,
    SR_FEATURE_SENSOR,
    SR_FEATURE_SUPPLY_POD,
    SR_FEATURE_MONOLITH,
    SR_FEATURE_MAGTUBE,
    SR_FEATURE_SOIL_ENRICHER,
    SR_FEATURE_ECH_MIRROR,
    SR_TERRAIN_TRENCH,
    SR_TERRAIN_ARID,
    SR_TERRAIN_MOIST,
    SR_TERRAIN_RAINY,
    SR_TERRAIN_HIGH,
    SR_TILE_YIELDS,
    SR_TILE_OWNER,
    SR_TILE_IN_RADIUS,
    SR_TILE_UNOWNED,
    SR_TILE_UNEXPLORED,

    // Scanner
    SR_SCAN_ALL,
    SR_SCAN_OWN_BASES,
    SR_SCAN_ENEMY_BASES,
    SR_SCAN_ENEMY_UNITS,
    SR_SCAN_OWN_UNITS,
    SR_SCAN_OWN_FORMERS,
    SR_SCAN_FUNGUS,
    SR_SCAN_PODS,
    SR_SCAN_IMPROVEMENTS,
    SR_SCAN_NATURE,
    SR_SCAN_NOT_FOUND,

    SR_BASE_AT,
    SR_UNIT_AT,
    SR_MORE_UNITS,

    // Base Screen
    SR_BASE_SCREEN,
    SR_SEC_OVERVIEW,
    SR_SEC_RESOURCES,
    SR_SEC_PRODUCTION,
    SR_SEC_ECONOMY,
    SR_SEC_FACILITIES,
    SR_SEC_STATUS,
    SR_FMT_OVERVIEW,
    SR_FMT_RESOURCES,
    SR_FMT_PRODUCTION,
    SR_FMT_QUEUE,
    SR_FMT_HURRY_COST,
    SR_FMT_ECONOMY,
    SR_FMT_FACILITIES,
    SR_FMT_FACILITIES_NONE,
    SR_FMT_STATUS,
    SR_FMT_STATUS_NORMAL,
    SR_FMT_DRONE_RIOTS,
    SR_FMT_GOLDEN_AGE,
    SR_FMT_ECO_DAMAGE,
    SR_FMT_GOVERNOR,
    SR_FMT_NERVE_STAPLE,
    SR_FMT_BASE_OPEN,

    // Base Screen (enhanced)
    SR_SEC_UNITS,
    SR_FMT_OVERVIEW_V2,
    SR_FMT_RESOURCES_V2,
    SR_FMT_PRODUCTION_V2,
    SR_FMT_ECONOMY_V2,
    SR_FMT_FACILITIES_V2,
    SR_FMT_UNITS,
    SR_FMT_UNITS_NONE,
    SR_FMT_BASE_OPEN_V2,
    SR_FMT_WORKERS,
    SR_BASE_HELP,
    SR_FMT_TURNS,
    SR_FMT_GROWTH_NEVER,
    SR_FMT_FACTION_CREDITS,
    SR_FMT_FACILITIES_COUNT,

    // Movement & Navigation
    SR_MOVEMENT_POINTS,
    SR_CANNOT_MOVE,

    // Context Help (Ctrl+F1)
    SR_HELP_HEADER,
    SR_HELP_MOVE,
    SR_HELP_EXPLORE,
    SR_HELP_SKIP,
    SR_HELP_HOLD,
    SR_HELP_READ,
    SR_HELP_GOTO,
    SR_HELP_BUILD_BASE,
    SR_HELP_BUILD_ROAD,
    SR_HELP_BUILD_MAGTUBE,
    SR_HELP_BUILD_FARM,
    SR_HELP_BUILD_MINE,
    SR_HELP_BUILD_SOLAR,
    SR_HELP_BUILD_FOREST,
    SR_HELP_BUILD_SENSOR,
    SR_HELP_BUILD_CONDENSER,
    SR_HELP_BUILD_BOREHOLE,
    SR_HELP_BUILD_AIRBASE,
    SR_HELP_BUILD_BUNKER,
    SR_HELP_REMOVE_FUNGUS,
    SR_HELP_AUTOMATE,
    SR_HELP_CONVOY,
    SR_HELP_UNLOAD,
    SR_HELP_OPEN_BASE,
    SR_HELP_MONOLITH,
    SR_HELP_SUPPLY_POD,
    SR_HELP_ATTACK,
    SR_HELP_PROBE,
    SR_HELP_AIRDROP,

    // Hurry feedback
    SR_HURRY_OK,
    SR_HURRY_NO_CREDITS,
    SR_HURRY_CANNOT,

    // Production Picker
    SR_PROD_PICKER_OPEN,
    SR_PROD_PICKER_ITEM,
    SR_PROD_PICKER_SELECT,
    SR_PROD_PICKER_CANCEL,
    SR_PROD_PICKER_EMPTY,
    SR_PROD_PICKER_CURRENT,
    SR_PROD_PICKER_CURRENT_NONE,
    SR_PROD_DETAIL_FAC,
    SR_PROD_DETAIL_PROJECT,
    SR_PROD_DETAIL_UNIT,
    SR_UNIT_ABILITIES,

    // Queue Management
    SR_QUEUE_OPEN,
    SR_QUEUE_OPEN_ONE,
    SR_QUEUE_ITEM,
    SR_QUEUE_ITEM_CURRENT,
    SR_QUEUE_MOVED,
    SR_QUEUE_REMOVED,
    SR_QUEUE_ADDED,
    SR_QUEUE_FULL,
    SR_QUEUE_CANNOT_MOVE_CURRENT,
    SR_QUEUE_CANNOT_REMOVE_CURRENT,
    SR_QUEUE_CLOSED,
    SR_QUEUE_EMPTY,

    // Menu Bar (world map)
    SR_MENU_GAME,
    SR_MENU_HQ,
    SR_MENU_NETWORK,
    SR_MENU_MAP,
    SR_MENU_ACTION,
    SR_MENU_TERRAFORM,
    SR_MENU_SCENARIO,
    SR_MENU_EDITMAP,
    SR_MENU_HELP,
    SR_MENU_CLOSED,
    SR_MENU_ENTRY_FMT,
    SR_MENU_ITEM_FMT,
    SR_MENU_ITEM_NOHK,
    SR_MENU_NAV_FMT,

    // Popup Menus
    SR_MENU_MAIN,           // "Main Menu"
    SR_MENU_MAP_MENU,       // "Map Menu"
    SR_MENU_MULTIPLAYER,    // "Multiplayer"
    SR_MENU_SCENARIO_MENU,  // "Scenario"
    SR_MENU_THINKER,        // "Thinker Menu"
    SR_MENU_GAME_MENU,      // "Game Menu"
    SR_MENU_FILE_SELECT,    // "File Selection" (Load/Save file picker)
    SR_FILE_LOAD_GAME,      // "Load Game"
    SR_FILE_SAVE_GAME,      // "Save Game"
    SR_FILE_FOLDER,         // "Folder"
    SR_FILE_ITEM_FMT,       // "%d of %d: %s, %s"  (pos, total, name, type)
    SR_FILE_PARENT_DIR,     // "Parent directory"
    SR_FILE_OVERWRITE_HINT, // "Enter to confirm, Escape to cancel"

    // Popup list navigation
    SR_POPUP_LIST_FMT,      // "%d of %d: %s"
    SR_POPUP_CONTINUE,      // "Enter to continue"

    // Social Engineering
    SR_SOCENG_TITLE,
    SR_SOCENG_CATEGORY_FMT,
    SR_SOCENG_MODEL_FMT,
    SR_SOCENG_EFFECTS,
    SR_SOCENG_NO_EFFECT,
    SR_SOCENG_UNAVAILABLE_TECH,
    SR_SOCENG_UNAVAILABLE_OPPOSITION,
    SR_SOCENG_SELECTED,
    SR_SOCENG_CURRENT,
    SR_SOCENG_PENDING,
    SR_SOCENG_SUMMARY_FMT,
    SR_SOCENG_UPHEAVAL_COST,
    SR_SOCENG_HELP,
    SR_SOCENG_CLOSED,

    // Preferences Handler
    SR_PREF_TITLE,
    SR_PREF_TAB_FMT,
    SR_PREF_OPTION_FMT,
    SR_PREF_TOGGLED_FMT,
    SR_PREF_SAVED,
    SR_PREF_CANCELLED,
    SR_PREF_HELP,
    SR_PREF_SUMMARY_FMT,
    SR_PREF_ENABLED,
    SR_PREF_DISABLED,

    // Preferences: Tab names
    SR_PREF_TAB_GENERAL,
    SR_PREF_TAB_WARNINGS,
    SR_PREF_TAB_ADVANCED,
    SR_PREF_TAB_AUTOMATION,
    SR_PREF_TAB_AUDIO_VISUAL,
    SR_PREF_TAB_MAP_DISPLAY,

    // Preferences: General tab
    SR_PREF_PAUSE_END_TURN,
    SR_PREF_AUTOSAVE,
    SR_PREF_QUICK_ENEMY,
    SR_PREF_TUTORIAL,
    SR_PREF_MOUSE_EDGE_SCROLL,
    SR_PREF_AUTO_DESIGN,
    SR_PREF_QUICK_ALLY,
    SR_PREF_AUTO_PRUNE,

    // Preferences: Warnings tab
    SR_PREF_WARN_FAC_BUILT,
    SR_PREF_WARN_NON_COMBAT_BUILT,
    SR_PREF_WARN_PROTOTYPE,
    SR_PREF_WARN_DRONE_RIOTS,
    SR_PREF_WARN_DRONE_RIOTS_END,
    SR_PREF_WARN_GOLDEN_AGE,
    SR_PREF_WARN_GOLDEN_AGE_END,
    SR_PREF_WARN_NUTRIENT_SHORTAGE,
    SR_PREF_WARN_BUILD_OUT_OF_DATE,
    SR_PREF_WARN_COMBAT_BUILT,
    SR_PREF_WARN_POP_LIMIT,
    SR_PREF_WARN_DELAY_TRANSCEND,
    SR_PREF_WARN_BUILT_VIA_QUEUE,
    SR_PREF_WARN_STARVATION,
    SR_PREF_WARN_MINERAL_SHORTAGE,
    SR_PREF_WARN_ENERGY_SHORTAGE,
    SR_PREF_WARN_RANDOM_EVENT,

    // Preferences: Advanced tab
    SR_PREF_FAST_BATTLE,
    SR_PREF_NO_CENTER_ORDERS,
    SR_PREF_PAUSE_AFTER_BATTLE,
    SR_PREF_ZOOM_NO_RECENTER,
    SR_PREF_QUICK_MOVE_ORDERS,
    SR_PREF_QUICK_MOVE_ALL,
    SR_PREF_RIGHT_CLICK_MENU,
    SR_PREF_DETAIL_RIGHT_CLICK,
    SR_PREF_CONFIRM_ODDS,
    SR_PREF_DETAIL_MAIN_MENUS,
    SR_PREF_RADIO_SINGLE_CLICK,

    // Preferences: Automation tab
    SR_PREF_FORMER_RAISE_LOWER,
    SR_PREF_FORMER_PLANT_FOREST,
    SR_PREF_FORMER_BUILD_ADV,
    SR_PREF_FORMER_REMOVE_FUNGUS,
    SR_PREF_FORMER_BUILD_SENSORS,
    SR_PREF_FORMER_BUILD_ROADS,
    SR_PREF_END_MOVE_PACT,
    SR_PREF_END_MOVE_TREATY,
    SR_PREF_END_MOVE_TRUCE,
    SR_PREF_END_MOVE_WAR,
    SR_PREF_END_MOVE_DIFF_TRIAD,
    SR_PREF_AIR_RETURN_HOME,
    SR_PREF_WAKE_ON_LAND,
    SR_PREF_ALWAYS_INSPECT_MONOLITH,

    // Preferences: Audio/Visual tab
    SR_PREF_SOUND_EFFECTS,
    SR_PREF_BACKGROUND_MUSIC,
    SR_PREF_MAP_ANIMATIONS,
    SR_PREF_SLIDING_WINDOWS,
    SR_PREF_PROJECT_MOVIES,
    SR_PREF_INTERLUDES,
    SR_PREF_VOICEOVER,
    SR_PREF_STOP_VOICE_CLOSE,
    SR_PREF_SLIDING_SCROLLBARS,
    SR_PREF_WHOLE_VEH_BLINKS,
    SR_PREF_MONUMENTS,

    // Preferences: Map Display tab
    SR_PREF_SHOW_GRID,
    SR_PREF_SHOW_BASE_GRID,
    SR_PREF_FOG_OF_WAR,
    SR_PREF_BASE_NAMES,
    SR_PREF_PROD_WITH_NAMES,
    SR_PREF_FLAT_TERRAIN,
    SR_PREF_GRID_OCEAN,
    SR_PREF_SHOW_GOTO_PATH,

    // Specialist Management (Ctrl+W)
    SR_SPEC_OPEN,
    SR_SPEC_CLOSE,
    SR_SPEC_WORKER,
    SR_SPEC_SPECIALIST,
    SR_SPEC_BONUS,
    SR_SPEC_TO_SPECIALIST,
    SR_SPEC_TO_WORKER,
    SR_SPEC_TYPE_CHANGED,
    SR_SPEC_CANNOT_MORE,
    SR_SPEC_CANNOT_LESS,
    SR_SPEC_CANNOT_CENTER,
    SR_SPEC_HELP,
    SR_SPEC_SUMMARY,
    SR_SPEC_CENTER,
    SR_SPEC_NO_OTHER_TYPE,
    SR_SPEC_WORKER_NO_TYPE,

    // Facility Demolition (Ctrl+D)
    SR_DEMOLITION_OPEN,
    SR_DEMOLITION_ITEM,
    SR_DEMOLITION_DETAIL,
    SR_DEMOLITION_CONFIRM,
    SR_DEMOLITION_DONE,
    SR_DEMOLITION_BLOCKED,
    SR_DEMOLITION_EMPTY,
    SR_DEMOLITION_CANCEL,

    // Targeting Mode & Go to Base
    SR_TARGETING_MODE,
    SR_TARGETING_CANCEL,
    SR_GO_TO_BASE,
    SR_BASE_LIST_FMT,
    SR_BASE_LIST_EMPTY,
    SR_GOING_HOME,
    SR_GOING_TO_BASE,
    SR_NO_UNIT_SELECTED,
    SR_HELP_GO_TO_BASE,
    SR_HELP_GO_HOME,
    SR_GROUP_GO_TO_BASE,
    SR_GROUP_GOING_TO_BASE,
    SR_HELP_GROUP_GOTO,
    SR_HELP_PATROL,
    SR_HELP_ARTILLERY,
    SR_HELP_SCAN_FILTER,
    SR_HELP_SCAN_JUMP,
    SR_AIRDROP_NO_ABILITY,
    SR_AIRDROP_BASE,
    SR_AIRDROP_BASE_FMT,
    SR_AIRDROP_CONFIRM,
    SR_AIRDROP_BLOCKED,
    SR_AIRDROP_CURSOR,
    SR_AIRDROP_CURSOR_CONFIRM,
    SR_AIRDROP_CURSOR_INVALID,

    // Diplomacy
    SR_DIPLO_OPEN,
    SR_DIPLO_CLOSED,
    SR_DIPLO_HELP,
    SR_DIPLO_SUMMARY,
    SR_DIPLO_STATUS_PACT,
    SR_DIPLO_STATUS_TREATY,
    SR_DIPLO_STATUS_TRUCE,
    SR_DIPLO_STATUS_VENDETTA,
    SR_DIPLO_STATUS_NONE,
    SR_DIPLO_PATIENCE,
    SR_DIPLO_PATIENCE_THIN,
    SR_DIPLO_PATIENCE_WEARING,
    SR_DIPLO_PATIENCE_OK,
    SR_DIPLO_SURRENDERED,
    SR_DIPLO_INFILTRATOR,
    SR_DIPLO_NETMSG,
    SR_DIPLO_COMMLINK_OPEN,
    SR_DIPLO_COMMLINK_ITEM,
    SR_DIPLO_COMMLINK_EMPTY,
    SR_DIPLO_COMMLINK_CONTACT,

    // Cursor / Numpad
    SR_CURSOR_TO_UNIT,

    // Turn Info
    SR_NEW_TURN,
    SR_UNIT_SKIPPED,
    SR_UNIT_DAMAGED,

    // Input dialogs
    SR_INPUT_NUMBER,
    SR_INPUT_NUMBER_EMPTY,
    SR_INPUT_NUMBER_DONE,

    // Design Workshop
    SR_DESIGN_PROTO_LIST,
    SR_DESIGN_PROTO_FMT,
    SR_DESIGN_CATEGORY,
    SR_DESIGN_CAT_CHASSIS,
    SR_DESIGN_CAT_WEAPON,
    SR_DESIGN_CAT_ARMOR,
    SR_DESIGN_CAT_REACTOR,
    SR_DESIGN_CHASSIS_FMT,
    SR_DESIGN_WEAPON_FMT,
    SR_DESIGN_ARMOR_FMT,
    SR_DESIGN_REACTOR_FMT,
    SR_DESIGN_ABILITY_FMT,
    SR_DESIGN_ABILITY_NONE,
    SR_DESIGN_COST,
    SR_DESIGN_SAVED,
    SR_DESIGN_CANCELLED,
    SR_DESIGN_NEW,
    SR_DESIGN_RETIRED,
    SR_DESIGN_RETIRE_CONFIRM,
    SR_DESIGN_HELP,
    SR_DESIGN_EDIT_HELP,
    SR_DESIGN_TRIAD_LAND,
    SR_DESIGN_TRIAD_SEA,
    SR_DESIGN_TRIAD_AIR,
    SR_DESIGN_EQUIPMENT,

    // Terraform Status
    SR_TERRAFORM_ORDER,
    SR_TERRAFORM_STATUS,
    SR_TERRAFORM_COMPLETE,

    // Nerve Staple (Ctrl+N)
    SR_NERVE_STAPLE_CONFIRM,
    SR_NERVE_STAPLE_DONE,
    SR_NERVE_STAPLE_CANNOT,

    // Base Rename (F2)
    SR_RENAME_OPEN,
    SR_RENAME_CHAR_FMT,
    SR_RENAME_DONE,
    SR_RENAME_CANCEL,

    // Base Open (extended announcement)
    SR_FMT_BASE_OPEN_NAME,
    SR_FMT_BASE_OPEN_RESOURCES,
    SR_FMT_BASE_OPEN_MOOD,
    SR_FMT_BASE_OPEN_PROD,

    // Governor Configuration (Ctrl+G)
    SR_GOV_TITLE,
    SR_GOV_OPTION_FMT,
    SR_GOV_ON,
    SR_GOV_OFF,
    SR_GOV_HELP,
    SR_GOV_SUMMARY_FMT,
    SR_GOV_SAVED,
    SR_GOV_CANCELLED,
    SR_GOV_PRIORITY_FMT,
    SR_GOV_PRIORITY_NONE,
    SR_GOV_PRIORITY_EXPLORE,
    SR_GOV_PRIORITY_DISCOVER,
    SR_GOV_PRIORITY_BUILD,
    SR_GOV_PRIORITY_CONQUER,

    // Social Engineering (extended)
    SR_SOCENG_TOTAL_EFFECTS,
    SR_SOCENG_NO_TOTAL_EFFECT,
    SR_SOCENG_ALLOC_FMT,
    SR_SOCENG_ALLOC_MODE,
    SR_SOCENG_ALLOC_SLIDER,
    SR_SOCENG_INFO_FMT,
    SR_SOCENG_ALLOC_ECON,
    SR_SOCENG_ALLOC_PSYCH,
    SR_SOCENG_ALLOC_LABS,

    // Garrison List (Ctrl+U)
    SR_GARRISON_OPEN,
    SR_GARRISON_ITEM,
    SR_GARRISON_DETAIL,
    SR_GARRISON_ACTIVATE,
    SR_GARRISON_HOME_SET,
    SR_GARRISON_EMPTY,
    SR_GARRISON_CLOSE,

    // Message Log (Ctrl+M)
    SR_MSG_OPEN,
    SR_MSG_ITEM,
    SR_MSG_ITEM_LOC,
    SR_MSG_EMPTY,
    SR_MSG_CLOSED,
    SR_MSG_NO_LOCATION,
    SR_MSG_SUMMARY,
    SR_MSG_HELP,
    SR_MSG_NOTIFICATION,

    // Time Controls (Shift+T)
    SR_TC_OPEN,
    SR_TC_ITEM,
    SR_TC_SET,
    SR_TC_CANCELLED,

    // Chat (Ctrl+C)
    SR_CHAT_OPEN,

    // Base Screen: Resources/Economy/Status V3
    SR_FMT_RESOURCES_V3,
    SR_FMT_STARVATION,
    SR_FMT_LOW_MINERALS,
    SR_FMT_ECONOMY_V3,
    SR_FMT_COMMERCE,
    SR_FMT_INEFFICIENCY,
    SR_FMT_NO_HQ,
    SR_FMT_HIGH_SUPPORT,
    SR_FMT_UNDEFENDED,
    SR_FMT_POLICE_UNITS,

    // Supported Units (Ctrl+Shift+S)
    SR_SUPPORT_OPEN,
    SR_SUPPORT_ITEM,
    SR_SUPPORT_DETAIL,
    SR_SUPPORT_EMPTY,
    SR_SUPPORT_CLOSE,
    SR_SUPPORT_ACTIVATE,

    // Psych Detail (Ctrl+Shift+Y)
    SR_PSYCH_DETAIL,

    // Base Help (updated)
    SR_BASE_HELP_V2,

    // Tile Assignment (Ctrl+T)
    SR_TILE_ASSIGN_OPEN,
    SR_TILE_ASSIGN_WORKED,
    SR_TILE_ASSIGN_AVAILABLE,
    SR_TILE_ASSIGN_CENTER,
    SR_TILE_ASSIGN_UNAVAIL,
    SR_TILE_ASSIGN_ASSIGNED,
    SR_TILE_ASSIGN_REMOVED,
    SR_TILE_ASSIGN_CANNOT_CENTER,
    SR_TILE_ASSIGN_CANNOT_UNAVAIL,
    SR_TILE_ASSIGN_CANNOT_NO_FREE,
    SR_TILE_ASSIGN_SUMMARY,
    SR_TILE_ASSIGN_CLOSE,
    SR_TILE_UNAVAIL_FOREIGN,
    SR_TILE_UNAVAIL_OTHER_BASE,
    SR_TILE_UNAVAIL_VEHICLE,
    SR_TILE_UNAVAIL_UNEXPLORED,

    // Patrol (P key)
    SR_PATROL_CONFIRM,
    SR_PATROL_CANNOT,
    SR_PATROL_PROMPT,

    // Road/Tube to cursor (Ctrl+R / Ctrl+T)
    SR_ROAD_TO_CONFIRM,
    SR_ROAD_TO_PROMPT,
    SR_TUBE_TO_CONFIRM,
    SR_TUBE_TO_PROMPT,
    SR_ROAD_TO_CANNOT,

    // Artillery (F key)
    SR_ARTY_CANNOT,
    SR_ARTY_NO_TARGETS,
    SR_ARTY_OPEN,
    SR_ARTY_TARGET_FMT,
    SR_ARTY_CURSOR,
    SR_ARTY_CURSOR_OOR,
    SR_ARTY_FIRED,
    SR_ARTY_HELP,

    // World Map Help (additional)
    SR_HELP_CURSOR_TO_UNIT,

    // Faction Status (Ctrl+F3)
    SR_STATUS_HEADER,
    SR_STATUS_CREDITS,
    SR_STATUS_ALLOC,
    SR_STATUS_INCOME,
    SR_STATUS_RESEARCH,
    SR_STATUS_RESEARCH_NONE,
    SR_STATUS_BASES,
    SR_STATUS_HELP,

    // Resource Bonuses (tile announcement)
    SR_BONUS_NUTRIENT,
    SR_BONUS_MINERAL,
    SR_BONUS_ENERGY,

    // Landmarks (tile announcement)
    SR_LANDMARK_CRATER,
    SR_LANDMARK_VOLCANO,
    SR_LANDMARK_JUNGLE,
    SR_LANDMARK_URANIUM,
    SR_LANDMARK_SARGASSO,
    SR_LANDMARK_RUINS,
    SR_LANDMARK_DUNES,
    SR_LANDMARK_FRESH,
    SR_LANDMARK_MESA,
    SR_LANDMARK_CANYON,
    SR_LANDMARK_GEOTHERMAL,
    SR_LANDMARK_RIDGE,
    SR_LANDMARK_BOREHOLE,
    SR_LANDMARK_NEXUS,
    SR_LANDMARK_UNITY,
    SR_LANDMARK_FOSSIL,

    // Move/View Mode (V key)
    SR_MODE_MOVE,
    SR_MODE_VIEW,

    // Multiplayer Setup (NetWin)
    SR_NETSETUP_OPEN,
    SR_NETSETUP_HELP,

    // Unit Action Menu (Shift+F10)
    SR_ACT_MENU_OPEN,
    SR_ACT_MENU_ITEM,
    SR_ACT_MENU_CANCEL,
    SR_ACT_MENU_EMPTY,
    SR_ACT_SKIP,
    SR_ACT_HOLD,
    SR_ACT_EXPLORE,
    SR_ACT_GOTO_BASE,
    SR_ACT_PATROL,
    SR_ACT_BUILD_ROAD,
    SR_ACT_BUILD_MAGTUBE,
    SR_ACT_BUILD_FARM,
    SR_ACT_BUILD_MINE,
    SR_ACT_BUILD_SOLAR,
    SR_ACT_BUILD_FOREST,
    SR_ACT_BUILD_SENSOR,
    SR_ACT_BUILD_CONDENSER,
    SR_ACT_BUILD_BOREHOLE,
    SR_ACT_BUILD_AIRBASE,
    SR_ACT_BUILD_BUNKER,
    SR_ACT_REMOVE_FUNGUS,
    SR_ACT_AUTOMATE,
    SR_ACT_BUILD_BASE,
    SR_ACT_LONG_RANGE,
    SR_ACT_CONVOY,
    SR_ACT_UNLOAD,
    SR_ACT_AIRDROP,
    SR_ACT_OPEN_BASE,
    SR_ACT_MENU_HELP,
    SR_ACT_DONE_HOLD,
    SR_ACT_DONE_EXPLORE,
    SR_ACT_DONE_UNLOAD,

    // Automation (Shift+A)
    SR_AUTO_OPEN,
    SR_AUTO_ITEM,
    SR_AUTO_CONFIRM,
    SR_AUTO_CANCEL,
    SR_AUTO_NOT_FORMER,
    SR_AUTO_FULL,
    SR_AUTO_ROAD,
    SR_AUTO_MAGTUBE,
    SR_AUTO_IMPROVE_BASE,
    SR_AUTO_FARM_SOLAR,
    SR_AUTO_FARM_MINE,
    SR_AUTO_FUNGUS,
    SR_AUTO_SENSOR,

    SR_COUNT
};

// Get localized string by ID (never returns NULL)
const char* loc(SrStr id);

// Load language file. Call once at startup after sr_init().
void loc_init();
